# Generated by Django 6.0.3 on 2026-03-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialeDag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('type', models.CharField(choices=[('feestdag', 'Feestdag'), ('uitstap', 'Uitstap'), ('studiedag', 'Studiedag')], default='feestdag', max_length=20)),
                ('beschrijving', models.CharField(blank=True, max_length=200)),
                ('is_wettelijk', models.BooleanField(default=False, help_text='Automatisch toegevoegde wettelijke feestdag')),
            ],
            options={
                'verbose_name': 'Speciale dag',
                'verbose_name_plural': 'Speciale dagen',
                'ordering': ['datum'],
            },
        ),
    ]
