# Generated by Django 6.0.3 on 2026-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialedag',
            name='is_wettelijk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='specialedag',
            name='type',
            field=models.CharField(choices=[('feestdag', 'Feestdag'), ('vakantie', 'Schoolvakantie'), ('studiedag', 'Studiedag'), ('sportdag', 'Sportdag'), ('andere', 'Andere')], default='studiedag', max_length=20),
        ),
    ]
