# Generated by Django 6.0.3 on 2026-03-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directie', '0002_alter_specialedag_is_wettelijk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialedag',
            name='type',
            field=models.CharField(choices=[('feestdag', 'Feestdag'), ('vakantie', 'Schoolvakantie'), ('pedagogische_studiedag', 'Pedagogische studiedag'), ('facultatieve_vrije_dag', 'Facultatieve vrije dag'), ('extra', 'Extra')], default='pedagogische_studiedag', max_length=30),
        ),
    ]
