# Generated by Django 6.0.3 on 2026-03-20 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directie', '0003_alter_specialedag_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afmelding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('reden', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('nieuw', 'Nieuw'), ('verwerkt', 'Verwerkt'), ('opgelost', 'Opgelost')], default='nieuw', max_length=20)),
                ('aangemaakt', models.DateTimeField(auto_now_add=True)),
                ('bijgewerkt', models.DateTimeField(auto_now=True)),
                ('leerkracht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afmeldingen', to=settings.AUTH_USER_MODEL)),
                ('vervanger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vervangingen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Afmelding',
                'verbose_name_plural': 'Afmeldingen',
                'ordering': ['-aangemaakt'],
            },
        ),
    ]
