# Generated by Django 6.0.3 on 2026-03-20 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directie', '0004_afmelding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vervanger_aangesteld', 'Vervanger aangesteld'), ('afmelding_ontvangen', 'Afmelding ontvangen')], max_length=30)),
                ('bericht', models.TextField()),
                ('gelezen', models.BooleanField(default=False)),
                ('aangemaakt', models.DateTimeField(auto_now_add=True)),
                ('afmelding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directie.afmelding')),
                ('ontvanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-aangemaakt'],
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaar', models.IntegerField()),
                ('maand', models.IntegerField()),
                ('aangemaakt', models.DateTimeField(auto_now_add=True)),
                ('aangemaakt_door', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning',
                'verbose_name_plural': 'Planningen',
                'ordering': ['-jaar', '-maand'],
                'unique_together': {('jaar', 'maand')},
            },
        ),
        migrations.CreateModel(
            name='Bewaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('moment', models.CharField(choices=[('ochtend', 'Ochtend'), ('middag', 'Middag'), ('namiddag', 'Namiddag')], max_length=10)),
                ('speelplaats', models.CharField(max_length=50)),
                ('leerkracht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bewakingen', to=settings.AUTH_USER_MODEL)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bewakingen', to='directie.planning')),
            ],
            options={
                'ordering': ['datum', 'moment'],
            },
        ),
    ]
