# Generated by Django 6.0.3 on 2026-03-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directie', '0005_notificatie_planning_bewaking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planning',
            unique_together=set(),
        ),
    ]
