# Generated by Django 6.0.3 on 2026-03-26 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesuur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag', models.CharField(choices=[('maandag', 'Maandag'), ('dinsdag', 'Dinsdag'), ('woensdag', 'Woensdag'), ('donderdag', 'Donderdag'), ('vrijdag', 'Vrijdag')], max_length=20)),
                ('vak', models.CharField(max_length=100)),
                ('begin_tijd', models.TimeField()),
                ('eind_tijd', models.TimeField()),
                ('klas', models.CharField(blank=True, max_length=50)),
                ('leerkracht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesuren', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesuur',
                'verbose_name_plural': 'Lesuren',
                'ordering': ['dag', 'begin_tijd'],
            },
        ),
    ]
