# Generated by Django 6.0.3 on 2026-03-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='werkregime',
            field=models.IntegerField(choices=[(100, 'Voltijds (100%)'), (80, '4/5 (80%)'), (75, '3/4 (75%)'), (50, 'Halftijds (50%)')], default=100, help_text='Werkpercentage van de leerkracht'),
        ),
    ]
